export const SHOP_LOADING = 'SHOP_LOADING';
export const SHOP_LOADING_MENU = 'SHOP_LOADING_MENU';
export const SHOP_PRODUCT_LOADING = 'SHOP_PRODUCT_LOADING';
export const SHOP_CART_LOADING = 'SHOP_CART_LOADING';
export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_ERROR = 'SAVE_DATA_ERROR';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
export const SHOP_FLUSH_DATA = 'SHOP_FLUSH_DATA';
export const SHOP_GET_MENU_SUCCESS = 'SHOP_GET_MENU_SUCCESS';
export const SHOP_GET_MENU_ERROR = 'SHOP_GET_MENU_ERROR';
export const SHOP_SET_FOOTER = 'SHOP_SET_FOOTER';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';
export const ADD_TO_CART = 'ADD_TO_CART';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SEARCH_PRODUCT_ALL = 'SEARCH_PRODUCT_ALL';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const SET_COMMENTS_SUCCESS = 'SET_COMMENTS_SUCCESS';
export const SET_COMPARE_PRODUCTS = 'SET_COMPARE_PRODUCTS';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CART_UPDATE = 'CART_UPDATE';
export const CLEAR_COMPARE_PRODUCTS = 'CLEAR_COMPARE_PRODUCTS';

export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_ERROR = 'ADD_ORDER_ERROR';

export const GET_PAYMENT_METHOD_ERROR = 'GET_PAYMENT_METHOD_ERROR';
export const GET_PAYMENT_METHOD_SUCCESS = 'GET_PAYMENT_METHOD_SUCCESS';

export const GET_PAYMENT_METHOD_SETTINGS_ERROR = 'GET_PAYMENT_METHOD_SETTINGS_ERROR';
export const GET_PAYMENT_METHOD_SETTINGS_SUCCESS = 'GET_PAYMENT_METHOD_SETTINGS_SUCCESS';

export const SET_PAYMENT_COMPLETE_SUCCESS = 'SET_PAYMENT_COMPLETE_SUCCESS';
export const SET_PAYMENT_COMPLETE_ERROR = 'SET_PAYMENT_COMPLETE_ERROR';

export const GET_SHIPPING_METHOD_SUCCESS = 'GET_SHIPPING_METHOD_SUCCESS';
export const GET_SHIPPING_METHOD_ERROR = 'GET_SHIPPING_METHOD_ERROR';

export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_ERROR = 'ORDER_ERROR';
