import productImg from '../../../assets/images/product/pro-item1.jpg';
import img1 from '../../../assets/images/ITSPK1-4825.jpg';

export const deals = [
  {
    innerTag: 'Hot',
    discount: -30,
    title: 'RCA-3D2 Replacement',
    price: 91.08,
    specialPrice: 88.6,
    imgSrc: productImg,
    detail: {
      title: 'Goyen® Pentair® Orignals®',
      images: [img1, img1, img1, img1],
      desc: 'Pentair® A Goyen® A Originals 071-0009 3/32 Barb to 10-32 UNF',
      ratings: 3,
      SKU: 'ITSPK1 5825',
      price: 91.08,
      specialPrice: 88.6,
      category: 'Taeha ® Repair Kits',
    },
  },
  {
    innerTag: 'Hot',
    discount: -30,
    title: 'Lorem Lipsum',
    price: 91.08,
    specialPrice: 88.6,
    imgSrc: productImg,
    detail: {
      title: 'Goyen® Pentair® Orignals®',
      images: [img1],
      desc: 'Pentair® A Goyen® A Originals 071-0009 3/32 Barb to 10-32 UNF',
      ratings: 4,
      SKU: 'ITSPK1 5825',
      price: 91.08,
      specialPrice: 88.6,
      category: 'Taeha ® Repair Kits',
    },
  },
  {
    innerTag: 'Hot',
    discount: -30,
    title: 'ABBA Dabba',
    price: 91.08,
    specialPrice: 88.6,
    imgSrc: productImg,
    detail: {
      title: 'Goyen® Pentair® Orignals®',
      images: [img1],
      desc: 'Pentair® A Goyen® A Originals 071-0009 3/32 Barb to 10-32 UNF',
      ratings: 4,
      SKU: 'ITSPK1 5825',
      price: 91.08,
      specialPrice: 88.6,
      category: 'Taeha ® Repair Kits',
    },
  },
  {
    innerTag: 'Hot',
    discount: -30,
    title: 'RCA - Replacement',
    price: 91.08,
    specialPrice: 88.6,
    imgSrc: productImg,
    detail: {
      title: 'Goyen® Pentair® Orignals®',
      images: [img1],
      desc: 'Pentair® A Goyen® A Originals 071-0009 3/32 Barb to 10-32 UNF',
      ratings: 5,
      SKU: 'ITSPK1 5825',
      price: 91.08,
      specialPrice: 88.6,
      category: 'Taeha ® Repair Kits',
    },
  },
  {
    innerTag: 'Hot',
    discount: -30,
    title: 'RCA-3D2 Replacement',
    price: 91.08,
    specialPrice: 88.6,
    imgSrc: productImg,
    detail: {
      title: 'Goyen® Pentair® Orignals®',
      images: [img1],
      desc: 'Pentair® A Goyen® A Originals 071-0009 3/32 Barb to 10-32 UNF',
      ratings: 2,
      SKU: 'ITSPK1 5825',
      price: 91.08,
      specialPrice: 88.6,
      category: 'Taeha ® Repair Kits',
    },
  },
];
