export const ACCOUNTS_LOADING = 'ACCOUNTS_LOADING';
export const ACCOUNTS_FLUSH_DATA = 'ACCOUNTS_FLUSH_DATA';

export const GET_ACCOUNTS_ORDERS_SUCCESS = 'GET_ACCOUNTS_ORDERS_SUCCESS';
export const GET_ACCOUNTS_ORDERS_ERROR = 'GET_ACCOUNTS_ORDERS_ERROR';


export const GET_ACCOUNTS_ORDERS_DETAIL_SUCCESS = 'GET_ACCOUNTS_ORDERS_DETAIL_SUCCESS';
export const GET_ACCOUNTS_ORDERS_DETAIL_ERROR = 'GET_ACCOUNTS_ORDERS_DETAIL_ERROR';


export const GET_ACCOUNTS_ORDERS_CANCEL_SUCCESS = 'GET_ACCOUNTS_ORDERS_CANCEL_SUCCESS';
export const GET_ACCOUNTS_ORDERS_CANCEL_ERROR = 'GET_ACCOUNTS_ORDERS_CANCEL_ERROR';


