export const LOAD_REPRESENTUS_SUCCESS = 'LOAD_REPRESENTUS_SUCCESS';
export const LOAD_REPRESENTUS_FAILURE = 'LOAD_REPRESENTUS_FAILURE';
export const REPRESENTUS_LOADING = 'REPRESENTUS_LOADING';
export const REPRESENTUS_GET_FAQ_SUCCESS = 'REPRESENTUS_GET_FAQ_SUCCESS';
export const REPRESENTUS_GET_FAQ_ERROR = 'REPRESENTUS_GET_FAQ_ERROR';